from _common.utils.exception import CommonException


class EvaluatorException(CommonException):
    pass
